### PR TITLE
Add openapi.json to repo instead to have an unverionized one in market repo

### PR DESCRIPTION
**Pull request by alexsuter**

### CODE REVIEW

**Comment by ivy-rew** [comment]
ok for me, although I don't see the benefit right now :-) 
I thought it will be accessible in the market anyway, as it is extracted at build time: https://github.com/axonivy-market/genderize-io-connector/blob/master/genderize-io-connector-product/pom.xml#L46

**Comment by alexsuter** [comment]
When this spec will change and we need to update the connector according to spec, then we don't know which spec matches to which connector. so it's versionized.

I'll remove all the special code handling for this unversionized stuff in the market website.

**Comment by alexsuter** [comment]
sorry I didn't know that this will be generated. I'll remove it again.

It was in the market repository, so I thought this will not be generated.

**Comment by ivy-rew** [comment]
thanks; no problem. In the end this openapi was crafted in this repo ... so not big issue if it actually lives here as source. 
while we are not adapting the openapi spec, both ways are ok.

**Pull request merged**
